version: '3.3'
services:
  envoy:
    build: .
    
    volumes:
      - $PWD/app:/app
    
    ports:
      - "8000:8000"
      - "9000:9000"
      - "1500:15000"

    expose:
      - "8000"
      - "9000"
      - "15000"
    
    container_name: envoy